FROM postgres AS Database
RUN apt-get update
ENV POSTGRES_USER: dbuser
ENV POSTGRES_PASSWORD: dbpassword
EXPOSE 5432
COPY ./initdb-scripts/*.sql ./docker-entrypoint-initdb.d/
FROM node:14-buster AS API

RUN apt-get update
WORKDIR /usr/src/app
COPY src /usr/src/app/src
COPY db /usr/src/app/db
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY . .
ENV DATABASE_CONNECTION_STRING: postgres://dbuser:dbpassword@db:5432/staffing

RUN npm ci --production
COPY ./start-script.sh .

EXPOSE 5432

EXPOSE 3000

EXPOSE 9229

CMD ["node", "/usr/src/app/src/app.js"]

ENTRYPOINT ["/usr/src/app/start-script.sh"]
